# Generated by Django 5.2.4 on 2025-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='last name'),
        ),
    ]
