# Generated by Django 5.2.4 on 2025-07-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Trắc nghiệm - Chọn 1'), ('MULTIPLE', 'Trắc nghiệm - Chọn nhiều'), ('TRUE_FALSE', 'Đúng / Sai'), ('FILL_IN_BLANK', 'Điền vào chỗ trống'), ('MATCHING', 'Ghép đôi')], default='SINGLE', max_length=20, verbose_name='Loại câu hỏi'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Nội dung lựa chọn / Đáp án'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Nội dung câu hỏi / Hướng dẫn'),
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255, verbose_name='Vế ghép (Prompt)')),
                ('answer', models.CharField(max_length=255, verbose_name='Vế trả lời (Answer)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs', to='quizapp.question')),
            ],
        ),
    ]
