# Generated by Django 5.2.4 on 2025-08-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Công khai'), ('PRIVATE', 'Riêng tư (yêu cầu mã)')], default='PUBLIC', max_length=10, verbose_name='Chế độ hiển thị'),
        ),
    ]
