# Generated by Django 5.2.4 on 2025-07-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_exam_subject_alter_result_score_alter_result_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('MATH', 'Toán'), ('PHYSICS', 'Vật lý'), ('CHEMISTRY', 'Hóa học'), ('BIOLOGY', 'Sinh học'), ('HISTORY', 'Lịch sử'), ('GEOGRAPHY', 'Địa lí'), ('CIVIC_EDUCATION', 'Giáo dục công dân'), ('OTHER', 'Môn khác')], default='OTHER', max_length=20, verbose_name='Môn học'),
        ),
    ]
