# Generated by Django 5.2.4 on 2025-07-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=50, verbose_name='Thời gian làm bài (phút)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('MATH', 'Toán'), ('PHYSICS', 'Vật lý'), ('CHEMISTRY', 'Hóa học'), ('BIOLOGY', 'Sinh học'), ('HISTORY', 'Lịch sử'), ('GEOGRAPHY', 'Địa lí'), ('CIVIC_EDUCATION', 'Giáo dục công dân'), ('ENGLISH', 'Tiếng Anh'), ('OTHER', 'Môn khác')], default='OTHER', max_length=20, verbose_name='Môn học'),
        ),
    ]
