# Generated by Django 5.2.4 on 2025-07-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_exam_duration_minutes_alter_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Cấu trúc tùy chỉnh'),
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề phần')),
                ('question_type', models.CharField(choices=[('SINGLE', 'Trắc nghiệm - Chọn 1'), ('MULTIPLE', 'Trắc nghiệm - Chọn nhiều'), ('TRUE_FALSE', 'Đúng / Sai'), ('FILL_IN_BLANK', 'Điền vào chỗ trống'), ('MATCHING', 'Ghép đôi')], max_length=20, verbose_name='Loại câu hỏi')),
                ('question_count', models.PositiveIntegerField(default=10, verbose_name='Số lượng câu')),
                ('points_per_question', models.FloatField(default=0.25, verbose_name='Điểm mỗi câu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự phần')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quizapp.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
