# Generated by Django 5.2.4 on 2025-07-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_exam_is_custom_examsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('MATH', 'Toán'), ('PHYSICS', 'Vật lý'), ('CHEMISTRY', 'Hóa học'), ('BIOLOGY', 'Sinh học'), ('HISTORY', 'Lịch sử'), ('GEOGRAPHY', 'Địa lí'), ('CIVIC_EDUCATION', 'Giáo dục công dân'), ('ENGLISH', 'Tiếng Anh'), ('OTHER', 'Môn khác')], default='OTHER', max_length=20, verbose_name='Môn học (cho cấu trúc chuẩn)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự trong phần'),
        ),
    ]
