# Generated by Django 5.2.4 on 2025-07-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_alter_exam_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề ngữ liệu')),
                ('content', models.TextField(verbose_name='Nội dung ngữ liệu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự ngữ liệu trong phần')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='quizapp.exam')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'order')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizapp.readingpassage', verbose_name='Ngữ liệu Đọc hiểu (nếu có)'),
        ),
    ]
