# Generated by Django 5.2.4 on 2025-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_alter_readingpassage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('MATH', 'Toán'), ('PHYSICS', 'Vật lý'), ('CHEMISTRY', 'Hóa học'), ('BIOLOGY', 'Sinh học'), ('HISTORY', 'Lịch sử'), ('GEOGRAPHY', 'Địa lí'), ('CIVIC_EDUCATION', 'Giáo dục công dân'), ('ENGLISH', 'Tiếng Anh'), ('TSA', 'Đánh giá tư duy (TSA)'), ('OTHER', 'Môn khác')], default='OTHER', max_length=20, verbose_name='Môn học (cho cấu trúc chuẩn)'),
        ),
    ]
