# Generated by Django 5.2.4 on 2025-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_user_date_of_birth_user_school_user_school_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
    ]
